### ISSUE TITLE
server.js comments

### ISSUE THREAD

**Issue by shiryz** [facn6/autocomplete-GAS#29]
- [ ] Your server.js is a file that starts the server and belongs in the src directory
- [x] You've required files you don't need in the sever like `words.js` and `autocomplete...`
- [x] `server.listen()` is an asynchronous method which takes a port and a callback, in your callback you can do whatever you need, e.g. logging the server is working, in your case you are logging outside of it either way and if your server isn't working you will get that log.

**Comment by ahdabSerhan** [comment]
* issue #34 
* deleted the words and autocomplete imports 
*added a callback function to server.listen

**Comment by samjam48** [comment]
First point relates #34
