### ISSUE TITLE
Building your url and sending an api request

### ISSUE THREAD

**Issue by shiryz** [facn6/autocomplete-GAS#39]
Here is how a url looks like 
https://github.com/m4v15/going-on-a-bear-hunt#url

After the `?` you have the query you need to check for, this is a better practice than adding endpoints because your search is not a new endpoint.
You can build this by using a form and submit on the frontend and you can use querystring on the backend to parse it.

**Comment by samjam48** [comment]
amended api request in front end
Changed to use URL object methods in back end to handle url and queryString for handling api search query data
